ARG UBUNTU_DIST=noble
FROM ubuntu:noble

ARG UBUNTU_DIST
ARG nushell_VERSION
ARG BUILD_VERSION
ARG FULL_VERSION
ARG ARCH
ARG NU_RELEASE

RUN mkdir -p /output/usr/bin
RUN mkdir -p /output/usr/share/doc/nushell
RUN mkdir -p /output/DEBIAN

COPY ${NU_RELEASE}/* /output/usr/bin/
RUN chmod 755 /output/usr/bin/nu /output/usr/bin/nu_plugin_*
COPY output/DEBIAN/control /output/DEBIAN/
COPY output/DEBIAN/postinst /output/DEBIAN/postinst
COPY output/DEBIAN/postrm /output/DEBIAN/postrm
RUN chmod 755 /output/DEBIAN/postinst /output/DEBIAN/postrm
COPY output/copyright /output/usr/share/doc/nushell/
COPY output/changelog.Debian /output/usr/share/doc/nushell/
COPY output/README.md /output/usr/share/doc/nushell/

RUN sed -i "s/DIST/$UBUNTU_DIST/" /output/usr/share/doc/nushell/changelog.Debian
RUN sed -i "s/FULL_VERSION/$FULL_VERSION/" /output/usr/share/doc/nushell/changelog.Debian
RUN gzip -9n /output/usr/share/doc/nushell/changelog.Debian
RUN sed -i "s/DIST/$UBUNTU_DIST/" /output/DEBIAN/control
RUN sed -i "s/nushell_VERSION/$nushell_VERSION/" /output/DEBIAN/control
RUN sed -i "s/BUILD_VERSION/$BUILD_VERSION/" /output/DEBIAN/control
RUN sed -i "s/SUPPORTED_ARCHITECTURES/$ARCH/" /output/DEBIAN/control

RUN dpkg-deb --build /output /nushell_${FULL_VERSION}.deb
